name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker-compose build

    - name: Start Docker container
      run: docker-compose up -d

    - name: Wait for container to start
      run: sleep 10

    - name: Run unit tests
      run: python manage.py test

    - name: Stop and clean up
      run: docker-compose down
